"""empty message

Revision ID: 24b96af44493
Revises: None
Create Date: 2016-06-23 23:49:36.550777

"""

# revision identifiers, used by Alembic.
revision = '24b96af44493'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_ip_coordinates')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_ip_coordinates',
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('geoname_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('accuracy_radius', sa.SMALLINT(), autoincrement=False, nullable=True)
    )
    ### end Alembic commands ###
